### ISSUE TITLE
I get token error

### ISSUE THREAD

**Issue by nyxb** [lannonbr/vsce-action#10]
`Run lannonbr/vsce-action@3.0.0
/usr/bin/docker run --name db2d783a4[6](https://github.com/VidarDev/VSC-Theme/runs/5376316535?check_suite_focus=true#step:5:6)9c4[7](https://github.com/VidarDev/VSC-Theme/runs/5376316535?check_suite_focus=true#step:5:7)7ca485e8495e9a72ae0b37a_8d3294 --label 7db2d7 --workdir /github/workspace --rm -e VSCE_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/VSC-Theme/VSC-Theme":"/github/workspace" 7db2d7:83a469c477ca485e8495e9a72ae0b37a publish -p $VSCE_TOKEN
error: option '-p, --pat <token>' argument missing`

**Comment by lannonbr** [comment]
Do you have the `VSCE_TOKEN` environment variable stored in the [GitHub Actions Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)?
